// frontend/src/lib/mock.ts
import type { ClipAnalysis, CorrelationSummary } from "./types";

export const MOCK_CLIPS: ClipAnalysis[] = [
  {
    clip_id: "ham_silverstone_2021_l52",
    source: "DATASET",
    driver: "HAM",
    race: "Silverstone 2021",
    lap: 52,
    session_type: "R",
    transcript: "Bono, my tyres are gone!",
    words: [
      { word: "Bono,", start: 0.12, end: 0.58 },
      { word: "my", start: 0.69, end: 0.81 },
      { word: "tyres", start: 0.84, end: 1.22 },
      { word: "are", start: 1.26, end: 1.41 },
      { word: "gone!", start: 1.44, end: 2.05 },
    ],
    asr_model: "openai/whisper-small",
    prosody: {
      arousal: 0.87,
      dominance: 0.64,
      valence: 0.21,
      speech_rate_wps: 3.94,
      pause_ratio: 0.08,
      mean_pause_s: 0.11,
      longest_pause_s: 0.34,
      rms_energy: 0.71,
      pitch_hz: 198.4,
      duration_s: 4.32,
      word_count: 17,
    },
    mood: {
      label: "STRESSED",
      confidence: 0.81,
      stress_index: 0.84,
      fatigue_index: 0.19,
      quadrant: "HIGH_AROUSAL_NEGATIVE",
      rationale: "High arousal (0.87) with negative valence (0.21) indicates acute stress. Speech rate 3.94 w/s is above the 3.2 w/s baseline.",
      contributing_factors: ["high_arousal", "negative_valence", "fast_speech", "high_volume"],
    },
    lap_context: {
      lap_number: 52,
      lap_time_s: 90.633,
      baseline_s: 89.412,
      delta_s: 1.221,
      next_lap_delta_s: 1.884,
      prev_lap_delta_s: 0.100,
      compound: "HARD",
      trend: "DEGRADING",
      window: [
        { lap_number: 50, lap_time_s: 89.512, delta_s: 0.100, compound: "HARD", stint: 2, tyre_life: 22, is_pit_lap: false, is_accurate: true, track_status: "1", is_radio_lap: false },
        { lap_number: 51, lap_time_s: 89.412, delta_s: 0.000, compound: "HARD", stint: 2, tyre_life: 23, is_pit_lap: false, is_accurate: true, track_status: "1", is_radio_lap: false },
        { lap_number: 52, lap_time_s: 90.633, delta_s: 1.221, compound: "HARD", stint: 2, tyre_life: 24, is_pit_lap: false, is_accurate: true, track_status: "1", is_radio_lap: true },
        { lap_number: 53, lap_time_s: 91.296, delta_s: 1.884, compound: "HARD", stint: 2, tyre_life: 25, is_pit_lap: false, is_accurate: true, track_status: "1", is_radio_lap: false },
        { lap_number: 54, lap_time_s: 91.501, delta_s: 2.089, compound: "HARD", stint: 2, tyre_life: 26, is_pit_lap: false, is_accurate: true, track_status: "1", is_radio_lap: false },
      ],
    },
    audio_peaks: [],
    audio_url: "/api/audio/ham_silverstone_2021_l52",
    processed_at: "2026-08-13T14:22:01Z",
    processing_ms: 1840,
    mocked: true,
  },
  {
    clip_id: "rai_abu_dhabi_2018_l53",
    source: "DATASET",
    driver: "RAI",
    race: "Abu Dhabi 2018",
    lap: 53,
    session_type: "R",
    transcript: "Leave me alone, I know what I'm doing.",
    words: [
      { word: "Leave", start: 0.20, end: 0.45 },
      { word: "me", start: 0.45, end: 0.60 },
      { word: "alone,", start: 0.60, end: 0.95 },
      { word: "I", start: 1.20, end: 1.30 },
      { word: "know", start: 1.30, end: 1.55 },
      { word: "what", start: 1.55, end: 1.70 },
      { word: "I'm", start: 1.70, end: 1.85 },
      { word: "doing.", start: 1.85, end: 2.30 },
    ],
    asr_model: "openai/whisper-small",
    prosody: {
      arousal: 0.52,
      dominance: 0.85,
      valence: 0.45,
      speech_rate_wps: 3.10,
      pause_ratio: 0.15,
      mean_pause_s: 0.25,
      longest_pause_s: 0.25,
      rms_energy: 0.42,
      pitch_hz: 145.2,
      duration_s: 3.50,
      word_count: 8,
    },
    mood: {
      label: "CALM",
      confidence: 0.76,
      stress_index: 0.28,
      fatigue_index: 0.12,
      quadrant: "HIGH_AROUSAL_POSITIVE",
      rationale: "Moderate arousal (0.52) with neutral valence indicates focus and calm.",
      contributing_factors: ["positive_valence"],
    },
    lap_context: {
      lap_number: 53,
      lap_time_s: 104.233,
      baseline_s: 104.850,
      delta_s: -0.617,
      next_lap_delta_s: -0.800,
      prev_lap_delta_s: -0.500,
      compound: "SOFT",
      trend: "IMPROVING",
      window: [
        { lap_number: 51, lap_time_s: 104.550, delta_s: -0.300, compound: "SOFT", stint: 2, tyre_life: 25, is_pit_lap: false, is_accurate: true, track_status: "1", is_radio_lap: false },
        { lap_number: 52, lap_time_s: 104.350, delta_s: -0.500, compound: "SOFT", stint: 2, tyre_life: 26, is_pit_lap: false, is_accurate: true, track_status: "1", is_radio_lap: false },
        { lap_number: 53, lap_time_s: 104.233, delta_s: -0.617, compound: "SOFT", stint: 2, tyre_life: 27, is_pit_lap: false, is_accurate: true, track_status: "1", is_radio_lap: true },
        { lap_number: 54, lap_time_s: 104.050, delta_s: -0.800, compound: "SOFT", stint: 2, tyre_life: 28, is_pit_lap: false, is_accurate: true, track_status: "1", is_radio_lap: false },
      ],
    },
    audio_peaks: [],
    audio_url: "/api/audio/rai_abu_dhabi_2018_l53",
    processed_at: "2026-08-13T14:22:02Z",
    processing_ms: 1650,
    mocked: true,
  },
  {
    clip_id: "vet_germany_2018_l52",
    source: "DATASET",
    driver: "VET",
    race: "Germany 2018",
    lap: 52,
    session_type: "R",
    transcript: "Sorry guys. I am... I am so sorry.",
    words: [
      { word: "Sorry", start: 0.10, end: 0.50 },
      { word: "guys.", start: 0.60, end: 1.10 },
      { word: "I", start: 2.50, end: 2.70 },
      { word: "am...", start: 2.70, end: 3.20 },
      { word: "I", start: 4.50, end: 4.70 },
      { word: "am", start: 4.70, end: 4.90 },
      { word: "so", start: 4.90, end: 5.20 },
      { word: "sorry.", start: 5.20, end: 5.80 },
    ],
    asr_model: "openai/whisper-small",
    prosody: {
      arousal: 0.25,
      dominance: 0.20,
      valence: 0.15,
      speech_rate_wps: 1.80,
      pause_ratio: 0.55,
      mean_pause_s: 1.35,
      longest_pause_s: 1.40,
      rms_energy: 0.15,
      pitch_hz: 110.5,
      duration_s: 6.50,
      word_count: 8,
    },
    mood: {
      label: "TIRED",
      confidence: 0.88,
      stress_index: 0.21,
      fatigue_index: 0.82,
      quadrant: "LOW_AROUSAL_NEGATIVE",
      rationale: "Low arousal (0.25) combined with long pauses (avg 1.35s) and slow speech rate (1.80 w/s) indicates exhaustion/fatigue.",
      contributing_factors: ["low_arousal", "negative_valence", "slow_speech", "long_pauses"],
    },
    lap_context: {
      lap_number: 52,
      lap_time_s: null,
      baseline_s: 76.210,
      delta_s: null,
      next_lap_delta_s: null,
      prev_lap_delta_s: 1.100,
      compound: "INTERMEDIATE",
      trend: "STABLE",
      window: [
        { lap_number: 50, lap_time_s: 77.110, delta_s: 0.900, compound: "INTERMEDIATE", stint: 2, tyre_life: 20, is_pit_lap: false, is_accurate: true, track_status: "2", is_radio_lap: false },
        { lap_number: 51, lap_time_s: 77.310, delta_s: 1.100, compound: "INTERMEDIATE", stint: 2, tyre_life: 21, is_pit_lap: false, is_accurate: true, track_status: "2", is_radio_lap: false },
        { lap_number: 52, lap_time_s: null, delta_s: null, compound: "INTERMEDIATE", stint: 2, tyre_life: 22, is_pit_lap: false, is_accurate: false, track_status: "4", is_radio_lap: true },
      ],
    },
    audio_peaks: [],
    audio_url: "/api/audio/vet_germany_2018_l52",
    processed_at: "2026-08-13T14:22:03Z",
    processing_ms: 1950,
    mocked: true,
  },
  {
    clip_id: "upload_mock_001",
    source: "UPLOAD",
    driver: null,
    race: null,
    lap: null,
    session_type: null,
    transcript: "",
    words: [],
    asr_model: "openai/whisper-small",
    prosody: {
      arousal: 0.10,
      dominance: 0.10,
      valence: 0.50,
      speech_rate_wps: null,
      pause_ratio: null,
      mean_pause_s: null,
      longest_pause_s: null,
      rms_energy: 0.05,
      pitch_hz: null,
      duration_s: 2.10,
      word_count: 0,
    },
    mood: {
      label: "UNKNOWN",
      confidence: 0.0,
      stress_index: 0.05,
      fatigue_index: 0.10,
      quadrant: "LOW_AROUSAL_POSITIVE",
      rationale: "Not enough speech detected to form a mood verdict.",
      contributing_factors: ["low_arousal"],
    },
    lap_context: null,
    audio_peaks: [],
    audio_url: "/api/audio/upload_mock_001",
    processed_at: "2026-08-13T14:22:04Z",
    processing_ms: 850,
    mocked: true,
  },
  {
    clip_id: "ham_hungary_2021_l45",
    source: "DATASET",
    driver: "HAM",
    race: "Hungary 2021",
    lap: 45,
    session_type: "R",
    transcript: "These guys are so fast on the straights, it's just impossible to get close enough in the corners to even make a move without destroying the tyres completely in the dirty air.",
    words: [
      { word: "These", start: 0.1, end: 0.3 },
      { word: "guys", start: 0.3, end: 0.5 },
      { word: "are", start: 0.5, end: 0.6 },
      { word: "so", start: 0.6, end: 0.7 },
      { word: "fast", start: 0.7, end: 1.0 },
      { word: "on", start: 1.0, end: 1.1 },
      { word: "the", start: 1.1, end: 1.2 },
      { word: "straights,", start: 1.2, end: 1.8 },
      { word: "it's", start: 1.9, end: 2.1 },
      { word: "just", start: 2.1, end: 2.3 },
      { word: "impossible", start: 2.3, end: 2.9 },
      { word: "to", start: 2.9, end: 3.0 },
      { word: "get", start: 3.0, end: 3.2 },
      { word: "close", start: 3.2, end: 3.5 },
      { word: "enough", start: 3.5, end: 3.8 },
      { word: "in", start: 3.8, end: 3.9 },
      { word: "the", start: 3.9, end: 4.0 },
      { word: "corners", start: 4.0, end: 4.5 },
      { word: "to", start: 4.5, end: 4.6 },
      { word: "even", start: 4.6, end: 4.8 },
      { word: "make", start: 4.8, end: 5.0 },
      { word: "a", start: 5.0, end: 5.1 },
      { word: "move", start: 5.1, end: 5.4 },
      { word: "without", start: 5.5, end: 5.8 },
      { word: "destroying", start: 5.8, end: 6.4 },
      { word: "the", start: 6.4, end: 6.5 },
      { word: "tyres", start: 6.5, end: 6.9 },
      { word: "completely", start: 6.9, end: 7.5 },
      { word: "in", start: 7.5, end: 7.6 },
      { word: "the", start: 7.6, end: 7.7 },
      { word: "dirty", start: 7.7, end: 8.0 },
      { word: "air.", start: 8.0, end: 8.4 },
    ],
    asr_model: "openai/whisper-small",
    prosody: {
      arousal: 0.78,
      dominance: 0.60,
      valence: 0.35,
      speech_rate_wps: 4.10,
      pause_ratio: 0.05,
      mean_pause_s: 0.05,
      longest_pause_s: 0.10,
      rms_energy: 0.65,
      pitch_hz: null,
      duration_s: 8.80,
      word_count: 32,
    },
    mood: {
      label: "STRESSED",
      confidence: 0.65,
      stress_index: 0.51,
      fatigue_index: 0.15,
      quadrant: "HIGH_AROUSAL_NEGATIVE",
      rationale: "High arousal with negative valence and fast speech rate (4.10 w/s) indicates stress.",
      contributing_factors: ["high_arousal", "negative_valence", "fast_speech"],
    },
    lap_context: {
      lap_number: 45,
      lap_time_s: 81.332,
      baseline_s: 79.510,
      delta_s: 1.822,
      next_lap_delta_s: 2.100,
      prev_lap_delta_s: 1.500,
      compound: "HARD",
      trend: "DEGRADING",
      window: [
        { lap_number: 43, lap_time_s: 80.810, delta_s: 1.300, compound: "HARD", stint: 2, tyre_life: 25, is_pit_lap: false, is_accurate: true, track_status: "1", is_radio_lap: false },
        { lap_number: 44, lap_time_s: 81.010, delta_s: 1.500, compound: "HARD", stint: 2, tyre_life: 26, is_pit_lap: false, is_accurate: true, track_status: "1", is_radio_lap: false },
        { lap_number: 45, lap_time_s: 81.332, delta_s: 1.822, compound: "HARD", stint: 2, tyre_life: 27, is_pit_lap: false, is_accurate: true, track_status: "1", is_radio_lap: true },
        { lap_number: 46, lap_time_s: 81.610, delta_s: 2.100, compound: "HARD", stint: 2, tyre_life: 28, is_pit_lap: false, is_accurate: true, track_status: "1", is_radio_lap: false },
        { lap_number: 47, lap_time_s: 81.910, delta_s: 2.400, compound: "HARD", stint: 2, tyre_life: 29, is_pit_lap: false, is_accurate: true, track_status: "1", is_radio_lap: false },
      ],
    },
    audio_peaks: [],
    audio_url: "/api/audio/ham_hungary_2021_l45",
    processed_at: "2026-08-13T14:22:05Z",
    processing_ms: 2500,
    mocked: true,
  },
];

export const MOCK_CORRELATION: CorrelationSummary = {
  n: 28,
  pearson_r: 0.61,
  p_value: 0.0006,
  pearson_r_next_lap: 0.44,
  mean_delta_by_mood: { CALM: -0.04, STRESSED: 0.83, TIRED: 0.51 },
  points: [
    { clip_id: "ham_silverstone_2021_l52", driver: "HAM", stress_index: 0.84, delta_s: 1.221, mood_label: "STRESSED" },
    { clip_id: "rai_abu_dhabi_2018_l53", driver: "RAI", stress_index: 0.28, delta_s: -0.617, mood_label: "CALM" },
    { clip_id: "vet_germany_2018_l52", driver: "VET", stress_index: 0.21, delta_s: 1.100, mood_label: "TIRED" },
    { clip_id: "ham_hungary_2021_l45", driver: "HAM", stress_index: 0.51, delta_s: 1.822, mood_label: "STRESSED" },
  ],
  headline: "Across 28 radio messages, stress index correlates with lap-time loss at r = 0.61 (p < 0.001). Messages flagged STRESSED averaged +0.83s versus the driver's clean-lap baseline."
};
